### ISSUE TITLE
Capacitor V3

### ISSUE THREAD

**Issue by Oupsla** [Scandit/scandit-capacitor-datacapture-core#1]
Hello folks 👋 

Capacitor V3 has been released for some time now and have some breaking changes about plugins (importing Plugins from '@capacitor/core' is now deprecating for example).

Info : https://capacitorjs.com/docs/updating/plugins/3-0

Do you have any plan to migrate your capacitor plugins ?

Thanks !

**Comment by ScanditSupport** [comment]
@Oupsla we're already supporting Capacitor 3 since our last release 6.9 (August 2021).

Release Notes:
https://docs.scandit.com/data-capture-sdk/capacitor/release-notes/6.9.html

In case of more detailed questions, please feel free to reach out to us directly:
https://support.scandit.com/hc/en-us/requests/new

Best regards
Scandit Support

**Comment by Oupsla** [comment]
Hello @ScanditSupport 

Yes, the plugin seems to work with Capacitor v3, but the usage is deprecated (and it will not work with futur versions)

Here are some logs : 

```
Capacitor WebPlugin "ScanditCaptureCorePlugin" config object was deprecated in v3 and will be removed in v4.
Capacitor plugin "ScanditCaptureCorePlugin" is using the deprecated "registerWebPlugin()" function
```

**Comment by ScanditSupport** [comment]
Hi @Oupsla 

thanks for the heads-up! We are  aware using deprecated methods using our plugin with Capacitor 3 due to compatibility reasons with older versions. 
We will ensure that this gets properly resolved as soon as Capacitor 4 appears on the horizon.

**Comment by aaronbach** [comment]
Are there any news, since Capacitor 4 is officially released now?

**Comment by ScanditSupport** [comment]
Hi @aaronbach 

Thank you for your message. 

We are now only compatible with Capacitor 3, but we are currently looking into it and plan to be compatible with Capacitor 4 as quickly as possible in an upcoming version of our SDK, depending on the QA process.

**Comment by aaronbach** [comment]
@ScanditSupport where can I get more Infos on the planned Releasedate for Capacitor 4 support? At the moment only Scandit prevents us from updating to Capacitor 4.

Thanks

**Comment by ScanditSupport** [comment]
Hi @aaronbach ,
 
We would like to inform you that 6.15-beta.1 has been released and it is compatible with Capacitor 4.
In case you still have troubles after updating the plugin, please reach out directly:
[Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)
