### ISSUE TITLE
Android Permissions on App startup

### ISSUE THREAD

**Issue by aaronbach** [Scandit/scandit-capacitor-datacapture-core#3]
At the moment I see no possibility, to handle the Camera Permission Request myself for Android. So when I open the App, which uses the Scandit Capacitor Plugin, I always get the Permission Dialog of Android because of this line: https://github.com/Scandit/scandit-capacitor-datacapture-core/blob/master/android/src/main/java/com/scandit/capacitor/datacapture/core/ScanditCaptureCoreNative.kt#L163

Please Support, that we can trigger this message ourself, or handle the permissions on the first scan.

**Comment by ScanditSupport** [comment]
Hi @aaronbach,

Please note that it was developed this way to keep our Capacitor SDK in line with the Cordova one. I have passed this point internally to include it in our planning for upcoming releases. 

I am afraid there is no workaround for this currently as it would require modifying the plugin itself. 

In case you have more detailed questions, please feel free to reach out to us directly: [Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)
