### ISSUE TITLE
Capacitor V4

### ISSUE THREAD

**Issue by lgoudin** [Scandit/scandit-capacitor-datacapture-core#5]
Hi,

As far as I'm aware, the only way to import the plugin is by doing this :

```typescript
import { ScanditCaptureCorePlugin } from 'scandit-capacitor-datacapture-core';
```

The issue with this is that we lose all the types and everything is of type `any`.

Do you plan on updating the plugin to capacitor v4 to allow the new import syntax?

**Comment by ScanditSupport** [comment]
Hi @lgoudin ,

I have checked it and it seems that we are currently working on the update.

If you want us to inform you about the progress, please get in contact with us directly via: https://support.scandit.com/hc/en-us/requests/new
