### ISSUE TITLE
Capacitor 6 support

### ISSUE THREAD

**Issue by jake-moritz-trifecta** [Scandit/scandit-capacitor-datacapture-core#6]
Is there a timeline for when this plugin will support Capacitor 6?

**Comment by ScanditSupport** [comment]
Hi Jake,

Thanks for reaching out.

At this moment we are working on making Capacitor 6 work with our SDK. I can't share any specific dates for when this will be available.

If you have any other questions or would like to be informed when we support Capacitor 6, please reach out to support@scandit.com
